name: Generate Badges

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["elinOS CI"]
    types:
      - completed

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
    - name: Create Build Badge
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
          echo "Build: Passing" 
        else
          echo "Build: Failing"
        fi 